### ISSUE TITLE
[Maker Commands] Add list of domains as a choice instead of having to enter it manually over and over again

### ISSUE THREAD

**Issue by keichinger** [Becklyn/ddd-generator-bundle#1]
The affected commands would be:

- `make:aggregate-root`
- `make:aggregate-handler`

When I run these commands, I don't necessarily want to write out my potentially very long domain name every time. Instead, what I'd want is the command to detect all available domains and list them alphabetically with a numerical index assigned to each domain, so that I can just type `0` to pick the first domain. If there is only a single option, it'll be automatically chosen and if there are multiple, a choice list will be rendered.

There are tons of other Symfony commands and even other CLI applications (e.g. `certbot`) which do it that way and the UX on using these commands is actually very very nice.

![CleanShot 2021-08-10 at 17 25 55](https://user-images.githubusercontent.com/439899/128894144-115f9ec3-4fc2-4b1f-bcd3-328b0cc23198.png)

The built-in Symfony example would be `security:encode-password`, which shows that choice list as soon as there are more than two user entities configured in your app: https://github.com/symfony/symfony/blob/e34cd7dd2c6d0b30d24cad443b8f964daa841d71/src/Symfony/Bundle/SecurityBundle/Command/UserPasswordEncoderCommand.php#L196-L215

**Comment by glassp** [comment]
Implemented in `v1.1.0` and `v2.1.0`
